






const posts = [
{id : 0, composer :{"FirstName" : "","LastName" : "Rachmaninoff", "image": "/imgs/rach.jpg" } , time : '1900 ', text : 'Piano concerto No.2:\n After the disastrous 1897 premiere of his First Symphony, Rachmaninoff suffered a psychological breakdown and depression that prevented composition for three years. In 1899, he was supposed to perform the Second Piano Concerto in London, which he had not composed yet, and instead made a successful conducting debut. The success led to an invitation to return next year with his First Piano Concerto; however, he promised to reappear with a newer and better one. After an unsuccessful meeting with Leo Tolstoy meant to revoke his writer\'s block, relatives decided to introduce Rachmaninoff to the neurologist Nikolai Dahl, whom he visited daily from January to April 1900. Rachmaninoff dedicated the concerto to Dahl for successfully treating him by restoring his health and confidence in composition.',comments: [{commentId: 0, commentText : "That's the best piece ever!" ,commentAuthor : "CoolPianist"}, {commentId: 1, commentText : "nice!" ,commentAuthor : "Arnon"}], contains_img: 1, img: '/imgs/rach.jpg', likes: 240},
{id : 1, composer : {"FirstName" : "","LastName" : "Beethoven", "image": "/imgs/beethoven.jpg" }, time : '1824', text : 'Symphony no. 9:\n the final complete symphony by Ludwig van Beethoven, composed between 1822 and 1824. It was first performed in Vienna on 7 May 1824. The symphony is regarded by many critics and musicologists as a masterpiece of Western classical music and one of the supreme achievements in the history of music. One of the best-known works in common practice music, it stands as one of the most frequently performed symphonies in the world.',comments: [{commentId: 0, commentText : "cool!" ,commentAuthor : "Mozart"}, {commentId: 1, commentText : "nice!" ,commentAuthor : "Arnon"}], contains_img :1, img: '/imgs/beethoven.jpg', likes: 6556},
{id : 2, composer :{"FirstName" : "J. S. ","LastName" : "Bach", "image": "/imgs/Johann_Sebastian_Bach.jpg" }, time : '1727', text : 'Ich habe genug',comments: [{commentId: 0, commentText : "cool!" ,commentAuthor : "Mozart"}, {commentId: 1, commentText : "nice!" ,commentAuthor : "Arnon"}], contains_img: 1, img: '/imgs/Johann_Sebastian_Bach.jpg', likes: 50},
{id : 3, composer :{"FirstName" : "","LastName" : "Chopin", "image": "/imgs/chopin.jpg" } , time : '1847', text : 'Ealz No.2 op.64',comments: [{commentId: 0, commentText : "cool!" ,commentAuthor : "Mozart"}, {commentId: 1, commentText : "nice!" ,commentAuthor : "Arnon"}], contains_img: 1, img:'/imgs/chopin.jpg', likes: 100},
{id : 4, composer :{"FirstName" : "","LastName" : "Mozart", "image": "/imgs/mozart.jpg" } , time : '1791', text : 'Requiem',comments: [{commentId: 0, commentText : "cool!" ,commentAuthor : "Mozart"}, {commentId: 1, commentText : "nice!" ,commentAuthor : "Arnon"}], contains_img: 1, img: '/imgs/mozart.jpg', likes: 130},
{id : 5, composer :{"FirstName" : "","LastName" : "Dvorak", "image": "/imgs/Dvorak.jpg" } , time : '1893', text : 'Symphony no. 9',comments: [{commentId: 0, commentText : "cool!" ,commentAuthor : "Mozart"}, {commentId: 1, commentText : "nice!" ,commentAuthor : "Arnon"}], contains_img: 1, img:'/imgs/Dvorak.jpg', likes: 998},
{id : 6, composer :{"FirstName" : "","LastName" : "Brahms", "image": "/imgs/brahms.jpg" } , time : '1885', text : 'Symphony No. 4',comments: [{commentId: 0, commentText : "cool!" ,commentAuthor : "Mozart"}, {commentId: 1, commentText : "nice!" ,commentAuthor : "Arnon"}], contains_img: 1, img: '/imgs/brahms.jpg', likes: 20},
{id : 7, composer :{"FirstName" : "","LastName" : "Tchaikovsky", "image": "/imgs/tchaikovsky.jpg" } , time : '1893', text : 'Symphony No. 6',comments: [{commentId: 0, commentText : "cool!" ,commentAuthor : "Mozart"}, {commentId: 1, commentText : "nice!" ,commentAuthor : "Arnon"}], contains_img: 1, img:'/imgs/tchaikovsky.jpg', likes: 278},
{id : 8, composer :{"FirstName" : "","LastName" : "Sibelius", "image": "/imgs/sibelius.jpg" } , time : '1904', text : 'Violin concerto',comments: [{commentId: 0, commentText : "cool!" ,commentAuthor : "Mozart"}, {commentId: 1, commentText : "nice!" ,commentAuthor : "Arnon"}], contains_img: 1, img: '/imgs/sibelius.jpg', likes: 30},
{id : 9, composer :{"FirstName" : "","LastName" : "Faure", "image": "/imgs/faure.jpg" } , time : '1888', text : 'Pavane',comments: [{commentId: 0, commentText : "cool!" ,commentAuthor : "Mozart"}, {commentId: 1, commentText : "nice!" ,commentAuthor : "Arnon"}], contains_img: 1, img:'/imgs/faure.jpg', likes: 453}
];

export default posts;

